### ISSUE TITLE
Chrome whitelist disables loading of local extensions

### ISSUE THREAD

**Issue by GERDebeka** [katalon-studio/katalon-studio#354]
Operating System: Windows 7, Windows 10
Katalon Studio Version: 7.4.0 (primarily) and 6.1.1

Google Chrome Version:  83.0.4103.116
ChromeDriver Version:  83.0.4103.39

Running a Test Case creates a dialog with the message (translated) "Error while loading the extension from: [user path]\AppData\Local\Temp\scoped_dir12345_0123456789\internal. Loading of unpacked extensions is disabled by the administrator."
This dialog pops up every time a browser window opens and must be closed manually to continue.

Same goes for the smart wait extension (  [installation path]\configuration\resources\extensions\Chrome\Smart wait) and Object Spy ( [installation path]\configuration\resources\extensions\Chrome\Object Spy\KR ) but the Object Spy cant detect / record any elements on a page, too.

Our company uses a policy (whitelist) for security reasons. That explain the message on every dialog.

Neither does the software offer a possibility to use only extensions from the company's default profile (Chrome) nor are all the named extensions on the official chrome web store.

How is it possible to execute tests / record elements from websites in Chrome with enabled whitelist?
Can the missing extensions be put on the chrome web store?
Or can Katalon Studio be configured to run without the internal extension? (because it runs fine after clicking the dialog)
![ks7Win10ChromeErrorExtensionLoading](https://user-images.githubusercontent.com/67589491/86015954-81f20e00-ba22-11ea-9d60-8b6f8990b548.PNG)

**Comment by minhthanh3145** [comment]
@GERDebeka 

Is my understanding correct ? These popups don't actually prevent you from using the recording/spying, but nonetheless pop up every time ?

**Comment by GERDebeka** [comment]
@minhthanh3145 
partly. The popups open on every opening new window (when starting object spy too).
But the spying isn't working at all: no detection (red quare around elements) and no capture notice (area with key combination and the selector).

I added screenshots from Firefox and Chrome for comparison.
![ks7win7ObjectSpyChrome](https://user-images.githubusercontent.com/67589491/86209466-f340d680-bb72-11ea-8b44-9ae66a9dbadb.png)
![ks7win7ObjectSpyFirefox](https://user-images.githubusercontent.com/67589491/86209471-f3d96d00-bb72-11ea-81a7-312cb669e56d.png)

**Comment by minhthanh3145** [comment]
@GERDebeka Ah I understand, the reason is that the extension for Firefox is packed and signed, while for Chrome it's loaded from a folder (unpacked). We will consider doing the same as Firefox for Chrome. Thank you for your report !

**Comment by jonesste12** [comment]
@minhthanh3145 are you with the Katalon development team and if so, when could this fix be available?  Thanks for your help.

**Comment by GERDebeka** [comment]
I checked the version 7.6.4 but sadly the error remains with an small change.

- test execution results with the same dialogs
- web recorder shows nearby the "(...)internal" dialog a second one with a generated extensionname (see picture)

In the meantime our environment changed, so the solution needs to fit for:
- windows 10 only (windows 7 wont be longer used by us for that purpose)
- chrome v84.0.4147.12 64bit

**Comment by minhthanh3145** [comment]
@GERDebeka 
Can you provide a screenshot for the issue with Web Recorder.

**Comment by GERDebeka** [comment]
I repeat my comment, cause github don't let me edit my privious one:

I checked the version 7.6.4 but sadly the error remains with a small change.

- test execution results with the same dialogs
- web recorder shows nearby the "(...)internal" dialog a second one with a generated extensionname (github file attachment don't work in the moment i posted it; i loaded the picture up on this link: https://imgur.com/wO9SqlL)

In the meantime our environment changed, so the solution needs to fit for:
- windows 10 only (windows 7 wont be longer used by us for that purpose)
- chrome v84.0.4147.12 64bit

We are waiting with high hopes for that solution.

**Comment by minhthanh3145** [comment]
@GERDebeka 

The path of the extension doesn't look right, the extension is supposed to be loaded from within Katalon Studio folder. Can you try to move Katalon Studio to another folder, re-activate it and delete `lib `bin` folders in your project, to eliminate the chances of caching issues.

**Comment by GERDebeka** [comment]
@minhthanh3145
i tried doing what you told me. Sadly nothing new happened.

**Comment by minhthanh3145** [comment]
@GERDebeka I'll try to reproduce the problem on my side. Thank you for your report !

**Comment by martyhammer** [comment]
My organization is experiencing similar problem with unpacked extension with naming convention:  C:\Users\xxx\AppData\Local\Temp\scoped_dirnnnnn_nnnnnnn\extension_abcdefg....  Loading of unpacked extensions is disabled by the administrator.   In our secure Chrome configuration, we have blacklisted "*" (all) and many items in Whitelist, including the initial Katalon Chrome extension.  However, we cannot whitelist the new extension created by the recorded in unpacked form.  If we remove the blacklist "*" entry (or change it to "dummy",  either way rendering the whitelist unnecessary), the error is avoided and the recorder (and playback) works correctly.   We only recently purchased this software and now can get no value from it.  When is a new release correcting this issue expected to be available?

**Comment by Padoplin** [comment]
Hello @martyhammer 

We fixed this issue in version 7.6.4. We're sorry for not updating this ticket earlier.  You're recommended to upgrade to the latest version, 7.7, which we officially released yesterday.

Jass

**Comment by AnshulVashisht** [comment]
Our company does have this version available, please suggest the solution for "Failed to Load Extension" issue in 7.6.2 version .

**Comment by jonesste12** [comment]
Is there a way to add code to the script so that it will bypass/ignore/accept the popup thus avoiding the manual intervention of clicking Ok?

**Comment by martyhammer** [comment]
This issue is still not resolved even with version 7.7.1.   You are failing
to understand my point.  In this environment, Chrome whitelist/blacklist is
enforced. Are there any corresponding whitelist codes to get past the
errors shows in these two messages we receive?  We are trying to record
simple test script with a CHROME browser.   (Works fine with Firefox.)

[image: image.png]
[image: image.png]




Martin L. Hammer, PMP® | GEO Client Engineering Manager
GEO Contract | SAIC Team | SAIC
Supporting GSA IT
Desk/Mobile: 703-676-4609
Email: martin.hammer@gsa.gov

**Comment by GERDebeka** [comment]
ok we had at least a partial breakthrough with the problem.

We added the ID of the extension "internal". The ID is: "nhjadcbdhpaglfenolfcepmoeifeaijd".
Set on the registry-entry: "HKEY_CURRENT_USER\Software\Policies\Google\Chrome\ExtensionInstallWhitelist" we solved with that the popup-dialog "internal".
Combined with disabling smart wait ("Project" -> "Settings"; "Execution" -> "Default,Smart Wait" = "Disable") which clear the popup-dialog "smart wait" unsatisfactory its possible tu run tests now without manuall work. *

Whats left is the function of "WebSpy" and "WebRecorder" which open the popup-dialog "KR".
We continue investigate that case and have a hunch on an other local extension "Katalon Utility" which ID we dont know.

But I personally also see it slowly like @martyhammer . We lose a lot of time here.

* This result was confirmed yesterday with the following environment: Windows 10 64bit, Chrome v85.0.4183.121 ChromeDriver v85.0.4183.121, Katalon Studio v7.4.0, v7.6.0, v7.6.4 and v7.7.0
![regeditKatalonStudioInternal](https://user-images.githubusercontent.com/67589491/94647720-5caabf80-02f1-11eb-9d4f-de978e130ae2.png)
![firefoxAddonOnWebSpy](https://user-images.githubusercontent.com/67589491/94647776-7e0bab80-02f1-11eb-98d5-349568945914.png)
![chromePopUpKROnWebRecorder](https://user-images.githubusercontent.com/67589491/94647778-7ea44200-02f1-11eb-8f74-33595f5e09a9.png)
![chromePopUpKROnWebSpy](https://user-images.githubusercontent.com/67589491/94647779-7f3cd880-02f1-11eb-93a7-75d6c874ec76.png)

**Comment by duyluonganh** [comment]
@GERDebeka @martyhammer 
We are investigating this issue.

The workaround here is:
- Disable Smart Wait feature as @GERDebeka mentioned
- Spy or record on Active Browser mode: https://docs.katalon.com/katalon-studio/docs/katalon-addon-for-chrome.html#port-configuration. It will let you spy or record on an opened session. 
![Screen Shot 2020-09-30 at 1 46 15 PM](https://user-images.githubusercontent.com/8241504/94652204-d3f94700-0323-11eb-8d88-38b5b78586be.png)

**Comment by GERDebeka** [comment]
@duyluonganh 
Sorry, i can't confirm your workaround.

We had the extension "Katalon Recorder (Selenium tests generator)" (ID: "ljdobmomdgdljniojadhoplhkpialdid") on Chrome already installed and on the whitelist enabled.

After selecting your shown Button there happended nothing. No Message, PopUp or any visible reaction at all nether for WebSpy or WebRecorder. *

I watched an example on Youtube to confirm that this behavior is wrong:
On "https://youtu.be/ApbxjPnrmW0?t=195" you can see between 3:15 - 4:13 how he does what you recommend (inclusive downloading that extension) and the chrome window / the WebRecorder from KS react on mouse movement and clicks.

If there is an other workaround please share it with us.

* This result was confirmed today with the following environment: Windows 10 64bit, Chrome v85.0.4183.121 with "Katalon Recorder (Selenium tests generator)" v5.3.1, ChromeDriver v85.0.4183.121, Katalon Studio v7.4.0, v7.6.0, v7.6.4 and v7.7.0

**Comment by duyluonganh** [comment]
Hi @GERDebeka 
> I watched an example on Youtube to confirm that this behavior is wrong:
On "https://youtu.be/ApbxjPnrmW0?t=195" you can see between 3:15 - 4:13 how he does what you recommend (inclusive downloading that extension) and the chrome window / the WebRecorder from KS react on mouse movement and clicks.

We think that his behavior was correct although his Katalon Studio version is quite old. We also record another video here: https://www.youtube.com/watch?v=hqkgkqe623w&feature=youtu.be. 
Please record a video to show that this feature doesn't work in your case.

**Comment by GERDebeka** [comment]
Hallo @duyluonganh 

thanks for posting an video how should look now, but your visible OS was macOS right?
That's not the same environment we use (Windows 10). The problem can't be replicated (with windows registry) like that.

I attached an clip of our environment (Windows 10, Chrome and Firefox for KSE 7.4.0) and how the workaround for WebRecorder with the Katalon Recorder plugin (on the browsers) only fails on chrome (sorry for the low quality, but github doesn't allow .mp4-files and limited filesize to 10MB).
![webRecorderBrokenActiveChromeOnly](https://user-images.githubusercontent.com/67589491/95063346-83f0fa80-06fe-11eb-880d-63116b777df8.gif)

I tested it with WebSpy on this configuration too; firefox works, chrome not.
I even tested it on our other versions of KSE (v7.6.0, v7.6.4 and v7.7.0); firefox works, chrome not. 

An interested colleague of me tried it at home on his private windows 10 machine with KS (and no black-/whitelist on the registry for chrome); Execution, WebSpy and WebRecorder worked fine!

For now i am 99% sure that the missing peace to solve this are the IDs from the chrome Extensions.
Please tell us the IDs for the three extensions:
"[KS-Filepath]/configuration/resources/extensions/Chrome/Object Spy/KR" (for WebSpy)
"[KS-Filepath]/configuration/resources/extensions/Chrome/Recorder/KR" (for WebRecorder)
"[KS-Filepath]/configuration/resources/extensions/Chrome/Recorder/Smart Wait" (for Smart Wait)

it was possible for you to send us "nhjadcbdhpaglfenolfcepmoeifeaijd"; the ID for the extension:
"[local default Chrome profile]/extension_nhjadcbdhpaglfenolfcepmoeifeaijd" (internal)

Or even better: publish all 4 extensions on the official chrome store (next to the already existing "Katalon Recorder"; ID "ljdobmomdgdljniojadhoplhkpialdid"). That would help us for some legal regulations too!

**Comment by GERDebeka** [comment]
Over two months passed since my last comment. Any progress so far?

**Comment by ccshubert** [comment]
Using Katalon 7.6.5 and still having this problem.

- In order to use Katalon Studio with Chrome in our controlled environment, we must disable Smart Wait.
- This is because the Smart Wait extension is an unpacked extension...
- ...but our controlled environment does not allow loading of unpacked extensions.
- Using Katalon+Chrome without Smart Wait does not work with our "responsive" Web Pages.

Please *create a packed, signed smart wait extension* for Chrome so that Katalon can be used with Chrome in controlled environments.

FYI, our environment is a US Federal Government Department.  I am sure that other Federal agencies use similar policies.  So, this basically impacts the entire Federal Government - a pretty big footprint!

**Comment by jridge** [comment]
I've just installed the latest version Katalon 7.9.0 and I'm running a Trial of the Enterprise edition.
Running on Win10 with Chrome version 87.0 and it still has the same issue (getting hung up on the Smart Wait).

It occurred to me that we could determine the "id" of the plugin by checking it on a machine that doesn't have the restriction on loading unpacked extensions.

That approach appeared to work and yielded the extension number for the "smart wait"

chrome://extensions/?id=loghpdeifonmghkjdanipmhkfjnkhjal

caveat - that extension came from Chrome v88, but I'm using v87 at the employer site so they could be different, but I'm guessing probably not.

Anyone configured to test my approach?  
LMK

PS: used following URL to figure out how to get the extension.  
https://www.bleepingcomputer.com/tutorials/how-to-find-id-for-chrome-extension/

**Comment by jridge** [comment]
Initial try results in no joy.  Next?

**Comment by GERDebeka** [comment]
@jridge 
nice idea, but unfortunately it did not work.
We added the ID "loghpdeifonmghkjdanipmhkfjnkhjal" to our registry. We also made sure that smart wait was enabled.
Result: The dialog still pops up. For test execution, web spy and web recorder.
![regedit](https://user-images.githubusercontent.com/67589491/108725738-f8e69480-7526-11eb-8102-c347953b0763.png)
![smartWaitEnabled](https://user-images.githubusercontent.com/67589491/108725751-fd12b200-7526-11eb-8912-032e5df1aae6.png)

After an webmeeting with the katalon support they informed us about an "All-In-One"-Extension they want to upload in the official chrome store.
For now we are waiting for that.

if anyone else has a good idea, we would still be interested in trying it out.

**Comment by martyhammer** [comment]
You are all missing the point regarding trying to "whitelist" the
extension.  THERE IS NO WAY TO WHITELIST UNPACKED EXTENSIONS. You cannot
use unpacked extensions if you are utilizing White/Blacklisting for the
packed extensions.


Martin L. Hammer, PMP® | GEO Client Engineering Manager
GEO Contract | SAIC Team | SAIC
Supporting GSA IT
Desk/Mobile: 703-676-4609
Email: martin.hammer@gsa.gov

**Comment by ccshubert** [comment]
Marty,

Yes, that is correct.  Until Katalon publishes their extensions in the Chrome App Store, Chrome cannot be used with Katalon on machines which have a managed extension whitelist - which includes, I suspect, all Federal machines and many machines owned by larger corporations.  This is a *huge* miss for Katalon.

Please see my issue, [Please Add Chrome Object Spy, Recorder, and Smart Wait Extensions to Google Web Store So That They Can Be Whitelisted|https://github.com/katalon-studio/katalon-studio/issues/444] requesting Katalon to take the necessary action.

At present, the issue appears to be stalled, and there does not appear to be a way to up-vote an issue, but at least it's out there!

Best,

Christopher C. Shubert

**Comment by hoop5318** [comment]
Dear all,
We have the same issue with the latest version of Katalon Studio this is still not solved. :-(

![image](https://user-images.githubusercontent.com/80841812/111496316-81c8a880-8740-11eb-8f11-36a6dcfca4bd.png)
We need a solution know otherwise we can't order this product for more users.

Best regards,
Christian

**Comment by nhpthuy** [comment]
Hi All,

In version 8.0.5 (download [here](https://www.katalon.com/download/), Katalon Studion introduced an option to Record Web with a packed extension, now available on the Chrome Web Store. See [Record Web Utility using Chrome with Profile](https://docs.katalon.com/katalon-studio/docs/record-web-utility-using-chrome-with-profile.html) for the user guide. For the rest extensions, we're working on them so pls stay tuned.

Also, pls have a look at our [Release note](https://docs.katalon.com/katalon-studio/new/version-8x.html) for further details.

Regards,
Shin

**Comment by jonesste12** [comment]
How do i get this download file and use it to install on a windows machine on a closed network, i want the sctual executable file

**Comment by Nam-Nguyen-Tran** [comment]
Hi everyone,

All the utilities are bundled into Katalon Compact Utility.
Please find its information here: https://docs.katalon.com/katalon-studio/docs/katalon-compact-utility.html#configuring-and-using-katalon-compact-utility-with-chrome-profile.

Thank you all for your concerns,
Nam Nguyen.

**Comment by ccshubert** [comment]
Thanks, @Nam-Nguyen-Tran!

I have requested that our IT department approve this extension.  This will address a longstanding and bothersome situation for us.  I'm looking forward to trying it!
